//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mini_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class sampledbEntities : DbContext
    {
        public sampledbEntities()
            : base("name=sampledbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin_details> admin_details { get; set; }
        public virtual DbSet<booking> bookings { get; set; }
        public virtual DbSet<cancellation> cancellations { get; set; }
        public virtual DbSet<train> trains { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<Nullable<double>> InsertBookingAndUpdateTrainWithDates(string customerName, Nullable<int> trainNo, string @class, Nullable<System.DateTime> date_of_Travel, Nullable<int> totalseats, ObjectParameter totalamount)
        {
            var customerNameParameter = customerName != null ?
                new ObjectParameter("customerName", customerName) :
                new ObjectParameter("customerName", typeof(string));
    
            var trainNoParameter = trainNo.HasValue ?
                new ObjectParameter("trainNo", trainNo) :
                new ObjectParameter("trainNo", typeof(int));
    
            var classParameter = @class != null ?
                new ObjectParameter("Class", @class) :
                new ObjectParameter("Class", typeof(string));
    
            var date_of_TravelParameter = date_of_Travel.HasValue ?
                new ObjectParameter("Date_of_Travel", date_of_Travel) :
                new ObjectParameter("Date_of_Travel", typeof(System.DateTime));
    
            var totalseatsParameter = totalseats.HasValue ?
                new ObjectParameter("Totalseats", totalseats) :
                new ObjectParameter("Totalseats", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("InsertBookingAndUpdateTrainWithDates", customerNameParameter, trainNoParameter, classParameter, date_of_TravelParameter, totalseatsParameter, totalamount);
        }
    
        public virtual ObjectResult<string> RegisterUser(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("RegisterUser", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<string> UserLogin(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UserLogin", usernameParameter, passwordParameter);
        }
    }
}
